---
title: "Practical Machine Learning"
output: html_document
---

Coursera's Data Science Specialization, Practical Machine Learning's project, Prediction Assignment Writeup.

##Background

Using devices such as JawboneUp, NikeFuelBand, and Fitbitit is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it.

In this project, the goal is to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website (see the section on the Weight Lifting Exercise Dataset).


#HTML report page (gh-pages)

Please open this GitHub link.

The HTML file is in the gh-pages branch.
The R markdown file (Rmd) is in the master branch.